### ISSUE TITLE
Consider including Portainer to ease docker-related tasks

### ISSUE THREAD

**Issue by klonos** [drevops/drevops#353]
https://www.portainer.io (https://github.com/portainer/portainer) is a great tool for managing local and remote Docker environments via a web UI:

> **Portainer** is a lightweight management UI which allows you to easily manage your different Docker environments (Docker hosts or Swarm clusters).
> 
> **Portainer** is meant to be as simple to deploy as it is to use. It consists of a single container that can run on any Docker engine (can be deployed as Linux container or a Windows native container).
> 
> **Portainer** allows you to manage your Docker containers, images, volumes, networks and more ! It is compatible with the standalone Docker engine and with Docker Swarm mode.

**Comment by AlexSkrypnyk** [comment]
Portainer can be installed globally and then used to managed containers between projects. DrevOps is a single project template - installing portainer with every project is not feasable.

Abandoning this one.
