### ISSUE TITLE
Native k8s support

### ISSUE THREAD

**Issue by fubarhouse** [drevops/drevops#426]
Any chance native k8s support is on your roadmap?

**Comment by alexdesignworks** [comment]
@fubarhouse Thanks you for your question.

Could you please expand on what kind of support you expect?

Right now, it's a pure docker config deployable to amazeeio Lagoon

**Comment by fubarhouse** [comment]
Drupal-Dev is defined as:
`a set of templates as well as an "attachable" development environment`

So, what exactly I'm after would be a series of deployment/service/route declarations to support adding a set of pods to a cluster - even if it's a Helm chart.

Amazee.io are working on this too so it may be premature but it's something I'm very interested in. Generally I've love support for vanilla k8s but I was just asking if it's available or planned outside of upstream work.

**Comment by alexdesignworks** [comment]
@fubarhouse 
it was not planned as a standalone set of config, but rather a deployment integration with another service (and if that service requires helm charts - they would be provided).

So for example, currently deployment to Acquia and Lagoon are supported out of the box. This means that the project has any and every means necessary to make deployments work.

I'm interested in adding a support for EKS or other service, but this is at least 2 iterations away.

Let's keep this issue open and I can come back to it a bit later.

Please feel free to add requirements list etc. here.

thanks

**Comment by AlexSkrypnyk** [comment]
No k8s work is planned here. Closing
