### ISSUE TITLE
[7.x] drush directory is not copied into containers

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/drevops#483]
it is ignore in `.dockerignore`. Need to include it in order to make sites relying on drush work.

**Comment by alexdesignworks** [comment]
Confirming that 8.x branch has this fixed. Still need to check 7.x branch.

**Comment by AlexSkrypnyk** [comment]
This looks like it is working 
https://github.com/drevops/drevops/blob/7.x/.dockerignore#L20
