### ISSUE TITLE
Invstigate adding drupal check

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/drevops#508]
https://github.com/mglaman/drupal-check

**Comment by alexdesignworks** [comment]
Autoloader does not work correctly, causing a lot of false positives.

Waiting for 1.0.12 release.

**Comment by AlexSkrypnyk** [comment]
With the version `1.1.5` released, this can be worked on.

**Comment by AlexSkrypnyk** [comment]
closed in favour of https://github.com/drevops/drevops/issues/614
