### ISSUE TITLE
Behat - explore options without Selenium

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/drevops#588]
https://gitlab.com/DMore/behat-chrome-extension

**Comment by AlexSkrypnyk** [comment]
This is a bit risky to apply to all projects. Abandoning for now.

**Comment by xurizaemon** [comment]
It's over at https://gitlab.com/behat-chrome/behat-chrome-extension now, hit me up if you're keen to give it a try :)

**Comment by AlexSkrypnyk** [comment]
Thank you @xurizaemon 
I will run some speed tests and will post here.

**Comment by xurizaemon** [comment]
Thanks Alex. Yeah I have no idea if that performance claim in the README will hold up years later - I'm sure there's been plenty of change both sides. Look forward to it!
