### ISSUE TITLE
Installer script not working

### ISSUE THREAD

**Issue by richardgaunt** [drevops/drevops#965]
`curl -SsL https://install.drevops.com | php`

The install script referenced in the README.md installs Drupal 9 (could be deliberate) but also breaks because `default.env.local` was renamed to `.env.local.example` but the installer gets the last released version 9 tag before this renaming happened.

The repository is not the same as the script so I cannot provide a PR.

**Comment by richardgaunt** [comment]
Also, https://github.com/drevops/drevops/blob/main/scripts/drevops/installer/install.php#L631 won't work with current logic as `10` will be the release prefix but I can see you have tagged your D10 releases as `1.x`

**Comment by AlexSkrypnyk** [comment]
Fixed in https://github.com/drevops/drevops/pull/976 and available in https://github.com/drevops/drevops/releases/tag/1.16.1
